### ISSUE TITLE
feat: Add support for freeRASP 5.0.0

### ISSUE THREAD

**Issue by yardexx** [yardexx/freerasp_brick#15]
**Description**

A new version of freeRASP deprecates iOS build script and introduces a new API.

**Tasks**

- [ ] Deprecate `scheme_updater.dart`
- [ ] Update template to match new API
- [ ] Add support for Dart 3.0
- [ ] Update version of mason
